version: "3.9"

services:

  app:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: ocr-delivery
    command: "./dev_start.sh"
    ports:
      - "8001:8000"
    env_file:
      - ./api/.env
    volumes:
      - ./api/src:/app/src
      - ./main_dir:/app/main_dir 


  